export { default as LogoIcon } from './logo.svg?react';
export { default as AlertIcon } from './alert.svg?react';
export { default as HamburgerIcon } from './hamburger.svg?react';
export { default as CloseIcon } from './close.svg?react';
export { default as MailIcon } from './mail.svg?react';
export { default as PhoneIcon } from './phone.svg?react';
export { default as LockIcon } from './lock.svg?react';
export { default as EyeIcon } from './eye.svg?react';
export { default as EyeOffIcon } from './eye-off.svg?react';
